### PR TITLE
pr-test

### PR DESCRIPTION
**Pull request by AriPerkkio**

### CODE REVIEW

**Comment by AriPerkkio** [comment]
@eslint-remote-tester-bot compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 9

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 3

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare --rules "{}"

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare --rules "{}"

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 4 --rules '{"no-undef": "error"}'

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 3

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare --rules '{"should crash": "when parsing json" 22" 123" '

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```json
{
  "eslintrc": {
    "rules": {
      "no-undef": "error"
    }
  }
}
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 5

```
{ 'rulesUnderTesting': ["no-undef"] }
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```
{ 'rulesUnderTesting': ["no-undef"] }
```

`\r`s removed

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```
{ 'rulesUnderTesting': ["local-rules/no-foo"], }
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```
{ 'rulesUnderTesting': ["no-undef"] should fail parsng
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```
{ 'rulesUnderTesting': "invalid config" }
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```
{ 'rulesUnderTesting': ["local-rules/no-foo"], }
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 3

```
{ 'rulesUnderTesting': [], }
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 6

```
{ 'rulesUnderTesting': ["local-rules/no-foo"], }
```

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```js
{ 
    'rulesUnderTesting': ["local-rules/no-foo"],
    onComplete: () => console.log('Custom onComplete'), 
}
```

5

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

```js
{ 
    'rulesUnderTesting': ["local-rules/no-foo"],
    onComplete: async (a, b) => {
        console.log('Custom onComplete');
        await new Promise(r => setTimeout(r, 5000));
        console.log('Results', a.length);
        await new Promise(r => setTimeout(r, 5000));
        console.log('Comparison added', b.added.length);
        await new Promise(r => setTimeout(r, 5000));
        console.log('Comparison removed', b.removed.length);
    } 
}
```

**Comment by sakkoja** [comment]
@github-actions eslint-remote-tester compare

Test, should deny permission

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions not-compare-action 1

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare 2

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare

**Comment by AriPerkkio** [comment]
@github-actions eslint-remote-tester compare
2

**Pull request closed without merging**
